datomicdb:
  build: datomic-pro-starter
  ports:
    - "4336:4336"
    - "4335:4335"
    - "4334:4334"
  volumes:
    - "/data"
waiter:
  image: aanand/wait
  links:
    - datomicdb
console:
  build: datomic-console
  ports:
    - "9000:9000"
  links:
    - waiter
    - datomicdb
